// File generated by Antigravity
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.linux:
      default:
        return windows; // Fallback to windows options for other desktop/mobile platforms as we only have Android config
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClNz0F6soAfmFoPPsmBqpTNvQXeRUQAe4',
    appId: '1:506321924173:android:4b1e784d77beab444e6c04',
    messagingSenderId: '506321924173',
    projectId: 'timbiriche-magico',
    databaseURL: 'https://timbiriche-magico-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = android;
}
